// import './__globals__.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Layout, Menu} from "antd";
import {AppstoreOutlined, MailOutlined} from "@ant-design/icons";
import React from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div>
            <Layout>
                <Menu items={[
                    {
                        label: 'Navigation One',
                        key: 'mail',
                        icon: <MailOutlined/>,
                    },
                    {
                        label: 'Navigation Two',
                        key: 'app',
                        icon: <AppstoreOutlined/>,
                        disabled: true,
                    },
                ]}/>
                <div>
                    {children}
                </div>
            </Layout>
        </div>
        </body>
        </html>
    )
}
